### ISSUE TITLE
chai-joi not compatible with Joi >= 13.1.1

### ISSUE THREAD

**Issue by EJB3927** [raisch/chai-joi#3]
Use joi: 13.1.1 or newer.

Example:
```js
const chai = require('chai');
const joi = require('joi');

chai.should();
chai.use(require('chai-joi'));

describe('.should.validate', function() {
  it('should validate', function() {
    let schema = joi.object().keys({
      'foo': joi.any().required(),
      'bar': joi.number().required()
    });
    let data = {'foo': 'bar', 'bar': 5};
    let result = joi.validate(data, schema);

    console.log(result);

    result.should.validate;
  });
});
```

Output:
```
$ mocha -- test/api-validation-test.js


  .should.validate
{ error: null,
  value: { foo: 'bar', bar: 5 },
  then: [Function: then],
  catch: [Function: catch] }
    1) should validate


  0 passing (13ms)
  1 failing

  1) .should.validate
       should validate:
     AssertionError: { Object (error, value, ...) } is not a validation because it contains unexpected keys
      at Function._chai.assert.isValidation (node_modules/chai-joi/index.js:232:34)
      at Assertion.validate (node_modules/chai-joi/index.js:122:15)
      at Assertion.propertyGetter (node_modules/chai/lib/chai/utils/addProperty.js:62:29)
      at Object.get (<anonymous>)
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:86:22)
      at Context.<anonymous> (test/api-validation-test.js:24:19)
```

**Comment by bigriot** [comment]
The fix is fairly simple.
The validation function needs to ignore 'then' and 'catch' from the resulting object from joi.validate()

```
var validation = function () {
  var target = this._obj;
  this.assert(_.isObject(target), '#{this} is not a Joi validation because it must be an object');
  this.assert(!_.isEmpty(target), '#{this} is not a Joi validation because it is an empty object');
  var fields = _.keys(target);
  this.assert(_.contains(fields, 'value', 'error'), '#{this} is not a Joi validation because it is missing required keys');
  target = _.omit(target, ['error', 'value', 'then', 'catch']);  <-- right here
  this.assert(_.isEmpty(target), '#{this} is not a validation because it contains unexpected keys');
};

```

**Comment by raisch** [comment]
Thanks. I'll look into it this weekend.

--
Rob Raisch, Internaut and Technocrat

**Comment by duereg** [comment]
https://github.com/raisch/chai-joi/pull/4
