### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by godievski** [raisch/chai-joi#8]
I just downloaded the npm package and it has merge conflicts and an older version of lodash. I cannot use it. Fix it asap.

**Comment by sschimmel** [comment]
```
tests\node_modules\chai-joi\index.js:88
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by bigriot** [comment]
Yeah chai-joi is pretty much broken ATM. Neither the incoming nor outgoing changes work.

**Comment by nikita-sheremet-clearscale** [comment]
Could you please publish working version to npm?

**Comment by raisch** [comment]
updated.
